version: 2.1
executors:
  default:
    docker:
      - image: circleci/golang:1.12.2
    working_directory: /go/src/github.com/mashiike/golicko
    environment:
      - GO111MODULE: "on"
      - TEST_RESULTS: /tmp/test-results
jobs:
  setup:
    executor:
      name: default
    steps:
      - checkout
      - run: mkdir -p $TEST_RESULTS
      - restore_cache:
          name: Restore go modules cache
          keys:
              - v1-mod-{{ .Branch }}-{{ checksum "go.mod" }}
      - run:
          command: go mod download
      - run: go get github.com/jstemmer/go-junit-report
      - save_cache:
          name: Save go modules cache
          key: v1-mod-{{ .Branch }}-{{ checksum "go.mod" }}
          paths:
              - /go/pkg/mod/cache
      - persist_to_workspace:
          root: /go
          paths:
              - pkg/mod/cache
              - bin
  tests:
    executor:
      name: default
    steps:
      - attach_workspace:
          at: /go
      - run:
          name: Run all unit tests
          command: |
            go test -v ./... | go-junit-report -set-exit-code=true > $TEST_RESULTS/go-test-report.xml
      - store_artifacts:
          path: /tmp/test-results
          destination: raw-test-output
      - store_test_results:
          path: /tmp/test-results

workflows:
  build-and-test:
    jobs:
      - setup
      - tests:
          requires:
            - setup
